# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: João Paquim
# email: joaopaquim@gmail.com
description: >
  My personal webpage, where you can find my blog and some of my projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jpaquim.com" # the base hostname & protocol for your site
github_username: jpaquim
permalink: /:categories/:title

# Build settings
markdown: kramdown

